[versions]
kotlin = "2.0.0"
navigation = "2.8.5"
hilt = "2.52"
compose = "1.7.6"
room = "2.6.1"
accompanist = "0.36.0"
work = "2.10.0"
exoplayer = "2.19.1"
paging = "3.3.5"
androidGradlePlugin = "8.5.2"
sentry = "4.10.0"
ksp = "2.0.0-1.0.23"
composeBom = "2025.01.00"
appcompat = "1.7.0"
lifecycle = "2.8.7"
browser = "1.8.0"
preference = "1.2.1"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.2"
gson = "2.11.0"
retrofit = "2.11.0"
okhttp = "5.0.0-alpha.14"
glide = "4.16.0"
glideCompose = "4.14.0"
coil = "2.7.0"
androidsvg = "1.4"
material = "1.12.0"
lottie = "6.6.0"
onboarding = "1.1.3"
shareAndroid = "1.0.0"
hiltNavigationCompose = "1.2.0"
startup = "1.2.0"
jsoup = "1.18.1"
socketIo = "2.1.1"
junit = "4.13.2"
archCoreTesting = "2.2.0"
mockito = "5.12.0"
mockitoKotlin = "5.4.0"
testMonitor = "1.7.2"
testRunner = "1.6.2"
testExtJunit = "1.2.1"
espresso = "3.6.1"
turbine = "1.1.0"
vicoCompose = "2.0.0-alpha.22"
composeRatingbar = "1.3.12"
loggerAndroid = "1.0.0"
compileSdk = "35"
targetSdk = "35"
minSdk = "22"
paletteKtx = "1.0.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltNavigationCompose" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

google-exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
google-exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
google-exoplayer-mediasession = { module = "com.google.android.exoplayer:extension-mediasession", version.ref = "exoplayer" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
androidsvg = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvg" }

material = { module = "com.google.android.material:material", version.ref = "material" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
onboarding = { module = "com.github.akshaaatt:Onboarding", version.ref = "onboarding" }
share-android = { module = "com.github.akshaaatt:Share-Android", version.ref = "shareAndroid" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
socket-io = { module = "io.socket:socket.io-client", version.ref = "socketIo" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "testExtJunit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.8.1" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTesting" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
androidx-test-monitor = { module = "androidx.test:monitor", version.ref = "testMonitor" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }

vico-compose = { module = "com.patrykandpatrick.vico:compose", version.ref = "vicoCompose" }
compose-ratingbar = { module = "com.github.a914-gowtham:compose-ratingbar", version.ref = "composeRatingbar" }
logger-android = { module = "com.github.akshaaatt:Logger-Android", version.ref = "loggerAndroid" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentry" }